### ISSUE TITLE
Puppet instead of scripts

### ISSUE THREAD

**Issue by nicpon** [OpenNebula/addon-context-windows#22]
Not really an issue, but I was wondering if anyone has given any thought (pros vs. cons) to using puppet or something alike to modify system configs instead of the scripts for both win and linux? 

Thanks and hope I don't get dinged for posting it here...
Cheers

**Comment by vholer** [comment]
Hi @nicpon,

depends on what you need to do. Scripts are great to start with, the syntax is well known among the power users, can be easily started from command line. If you don't have too many complicated tasks, it's fine. If nothing else, it can be used to **bootstrap the Puppet and leave the rest on it**.

About Puppet itself, it's usually more work than writing simple one-shot scripts. At first, you must have a Puppet server (master) deployed to serve the recipes to nodes (agents). Or, in a masterless setup, you must prepare your own way how to get and run recipes on the managed node. The Puppet uses own DSL, some people say it's confusing. The actions are designed to be idempotent, so you can run it several times, but the change is done only once. There are many modules (https://forge.puppet.com/) to easily manage many many many things on Linux or Windows.

There are more automation tools, please see:
http://blog.takipi.com/deployment-management-tools-chef-vs-puppet-vs-ansible-vs-saltstack-vs-fabric/

So, it's only about your own use-cases, infrastructure size and time.

Thank you for your question, since it's not an issue, I'll close it for now. For further questions, you can use https://forum.opennebula.org/. Maybe, there some people bootstrapping the Puppet on Windows VMs.

Best regards,
Vlastimil Holer
